### ISSUE TITLE
VVVVVV crashes with new SDLdyn patch

### ISSUE THREAD

**Issue by clementgallet** [clementgallet/libTAS#162]
Crash at startup. Here's the backtrace:
```
Thread 1 "vvvvvv.x86_64" received signal SIGSEGV, Segmentation fault.
0x00007ffff7c3a8e0 in ?? () from /home/clement/Games/vvvvvv/x86_64/libSDL2-2.0.so.0
(gdb) bt
#0  0x00007ffff7c3a8e0 in ?? () from /home/clement/Games/vvvvvv/x86_64/libSDL2-2.0.so.0
#1  0x00007ffff7c3aef7 in ?? () from /home/clement/Games/vvvvvv/x86_64/libSDL2-2.0.so.0
#2  0x00007ffff7c3efe1 in ?? () from /home/clement/Games/vvvvvv/x86_64/libSDL2-2.0.so.0
#3  0x00007ffff7ca07cd in ?? () from /home/clement/Games/vvvvvv/x86_64/libSDL2-2.0.so.0
#4  0x00007ffff7c47b25 in ?? () from /home/clement/Games/vvvvvv/x86_64/libSDL2-2.0.so.0
#5  0x00007ffff7f3aa5c in libtas::SDL_CreateWindowAndRenderer (width=640, height=480, window_flags=32, window=0x7fffffffc248, renderer=0x7fffffffc250)
    at /home/clement/libtas-1.3.2/src/library/sdlwindows.cpp:318
#6  0x000000000056015b in Screen::Screen() ()
#7  0x0000000000416a5b in main ()
```

If I replace the SDL2 library bundled with the game (2.0.3) with my own system library (2.0.9), it works fine. I should try to get my hand on a library with symbols.

**Comment by clementgallet** [comment]
I found debug symbols for version 2.0.2. Here is the bactrace:
```
(gdb) bt
#0  SDL_AddEvent (event=0x7fffffffc060) at /build/libsdl2-GU6pAZ/libsdl2-2.0.2+dfsg1/src/events/SDL_events.c:221
#1  SDL_PeepEvents_REAL (events=<optimized out>, numevents=1, action=<optimized out>, minType=0, maxType=<optimized out>) at /build/libsdl2-GU6pAZ/libsdl2-2.0.2+dfsg1/src/events/SDL_events.c:283
#2  0x00007ffff7c316a6 in SDL_PushEvent_REAL (event=event@entry=0x7fffffffc060) at /build/libsdl2-GU6pAZ/libsdl2-2.0.2+dfsg1/src/events/SDL_events.c:471
#3  0x00007ffff7c356a5 in SDL_SendWindowEvent (window=window@entry=0xb5cdd0, windowevent=windowevent@entry=1 '\001', data1=data1@entry=0, data2=data2@entry=0)
    at /build/libsdl2-GU6pAZ/libsdl2-2.0.2+dfsg1/src/events/SDL_windowevents.c:197
#4  0x00007ffff7c94b56 in SDL_ShowWindow_REAL (window=window@entry=0xb5cdd0) at /build/libsdl2-GU6pAZ/libsdl2-2.0.2+dfsg1/src/video/SDL_video.c:1786
#5  0x00007ffff7c9588e in SDL_FinishWindowCreation (window=window@entry=0xb5cdd0, flags=flags@entry=32) at /build/libsdl2-GU6pAZ/libsdl2-2.0.2+dfsg1/src/video/SDL_video.c:1203
#6  0x00007ffff7c976d4 in SDL_CreateWindow_REAL (title=title@entry=0x0, x=x@entry=536805376, y=y@entry=536805376, w=640, h=480, flags=32) at /build/libsdl2-GU6pAZ/libsdl2-2.0.2+dfsg1/src/video/SDL_video.c:1297
#7  0x00007ffff7c3d4f5 in SDL_CreateWindowAndRenderer_REAL (width=<optimized out>, height=<optimized out>, window_flags=<optimized out>, window=0x7fffffffc258, renderer=0x7fffffffc260)
    at /build/libsdl2-GU6pAZ/libsdl2-2.0.2+dfsg1/src/render/SDL_render.c:187
#8  0x00007ffff7f3aa5c in libtas::SDL_CreateWindowAndRenderer (width=640, height=480, window_flags=32, window=0x7fffffffc258, renderer=0x7fffffffc260) at /home/clement/libtas-1.3.2/src/library/sdlwindows.cpp:318
#9  0x000000000056015b in Screen::Screen() ()
#10 0x0000000000416a5b in main ()
```

**Comment by clementgallet** [comment]
The game works correctly with version 2.0.4.

**Comment by jacobly0** [comment]
Working on it at #180.
