### ISSUE TITLE
Mouse button input is broken in The Talos Principle

### ISSUE THREAD

**Issue by iamgreaser** [clementgallet/libTAS#188]
I had to see why clicking buttons was crashing and ended up finding a bit more out.

As it turns out, clicking crashes when in the *menu*, the crash usually happens mostly when you are attempting a left mouse button click but I managed to get it to crash with a middle click... although I may have somehow scrolled the wheel in the process.

However, clicking does NOT crash the main game. Instead, right mouse seems to report a middle click, middle mouse seems to report a left click, and left mouse straight up doesn't seem to do much at all.

Crash log from GDB:
```
Thread 1 (Thread 0x7ffff5774d40 (LWP 2798)):
#0  0x00000000019f35fa in ?? ()
#1  0x0000000001a6736f in ?? ()
#2  0x0000000001a7e4e2 in ?? ()
#3  0x0000000000934387 in ?? ()
#4  0x00000000009364ef in ?? ()
#5  0x00000000014b4c0a in ?? ()
#6  0x000000000196c502 in ?? ()
#7  0x000000000196c7e4 in ?? ()
#8  0x00007ffff790e09b in __libc_start_main (main=0x4464e0, argc=1, argv=0x7fffffffe788, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe778) at ../csu/libc-start.c:308
#9  0x0000000000921d47 in ?? ()
```

And the other threads with a bit of deduping:
```
Thread 10 (Thread 0x7fffdcd0b700 (LWP 2844)):
#0  0x00007ffff7c44b20 in __GI___nanosleep (requested_time=0x7fffdcd0aba0, remaining=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007ffff7f0afba in usleep () from /usr/local/bin/libtas.so
#2  0x0000000001b2676f in ?? ()
#3  0x00000000019d3622 in ?? ()
#4  0x0000000001a5e35d in ?? ()
#5  0x00007ffff7f0b9a8 in libtas::pthread_start(void*) () from /usr/local/bin/libtas.so
#6  0x00007ffff7c3af93 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007ffff79e37cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7fffdeffd700 (LWP 2843)):
Thread 8 (Thread 0x7fffdf7fe700 (LWP 2842)):
Thread 7 (Thread 0x7fffdffff700 (LWP 2841)):
Thread 6 (Thread 0x7fffe4e11700 (LWP 2840)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x3a0d9ec) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x3a0d998, cond=0x3a0d9c0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x3a0d9c0, mutex=0x3a0d998) at pthread_cond_wait.c:655
#3  0x00007ffff7f0c3cd in pthread_cond_wait () from /usr/local/bin/libtas.so
#4  0x00007fffeb370ab3 in ?? () from /usr/lib/xorg/modules/drivers/swrast_dri.so
#5  0x00007fffeb370a27 in ?? () from /usr/lib/xorg/modules/drivers/swrast_dri.so
#6  0x00007ffff7f0b9a8 in libtas::pthread_start(void*) () from /usr/local/bin/libtas.so
#7  0x00007ffff7c3af93 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007ffff79e37cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 20 (Thread 0x7fffb6d8c700 (LWP 2879)):
Thread 18 (Thread 0x7fffb758d700 (LWP 2853)):
Thread 17 (Thread 0x7fffb7d8e700 (LWP 2852)):
Thread 16 (Thread 0x7fffc3fff700 (LWP 2851)):
Thread 11 (Thread 0x7fffce109700 (LWP 2846)):
Thread 5 (Thread 0x7ffff341c700 (LWP 2839)):
Thread 4 (Thread 0x7ffff3fe2700 (LWP 2838)):
Thread 3 (Thread 0x7ffff47e3700 (LWP 2837)):
Thread 2 (Thread 0x7ffff4ff4700 (LWP 2836)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7ffff50044e0) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7ffff50044e8, cond=0x7ffff50044b8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7ffff50044b8, mutex=0x7ffff50044e8) at pthread_cond_wait.c:655
#3  0x00007ffff7f0c3cd in pthread_cond_wait () from /usr/local/bin/libtas.so
#4  0x0000000001a5ffeb in ?? ()
#5  0x00000000019d364c in ?? ()
#6  0x0000000001a5e35d in ?? ()
#7  0x00007ffff7f0b9a8 in libtas::pthread_start(void*) () from /usr/local/bin/libtas.so
#8  0x00007ffff7c3af93 in start_thread (arg=<optimized out>) at pthread_create.c:486
#9  0x00007ffff79e37cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Anyway, walking the stack:

```
   0x00000000019f35f0:	mov    0xd8(%rbx),%edx
   0x00000000019f35f6:	test   %edx,%edx
   0x00000000019f35f8:	je     0x19f364e
=> 0x00000000019f35fa:	testb  $0x10,(%r12)
   0x00000000019f35ff:	je     0x19f364e
   0x00000000019f3601:	cmpl   $0x1,0x28(%rbp)
   0x00000000019f3605:	jne    0x19f35af
   0x00000000019f3607:	mov    (%rbx),%rax
   0x00000000019f360a:	mov    %rbx,%rdi
   0x00000000019f360d:	callq  *0xc0(%rax)
   0x00000000019f3613:	mov    %eax,%edx
   0x00000000019f3615:	mov    %rax,(%rsp)
```

r12 is 0. Calling convention suggests this is being jumped to from somewhere as R12 is callee-preserved and is not an argument register.

Sure enough:

```
   0x00000000019f3550:	mov    0xb0(%rdi),%r13
   0x00000000019f3557:	mov    %rdx,0xb0(%rbx)
   0x00000000019f355e:	mov    %rsi,%r12
   0x00000000019f3561:	mov    (%rdx),%eax
   0x00000000019f3563:	mov    %rdx,%rbp
   0x00000000019f3566:	test   %eax,%eax
   0x00000000019f3568:	jne    0x19f3584
   0x00000000019f356a:	mov    0x78(%rdi),%rsi
   0x00000000019f356e:	test   %rsi,%rsi
   0x00000000019f3571:	je     0x19f35af
   0x00000000019f3573:	cmp    %rsi,%r12 <--- that might be our register!
   0x00000000019f3576:	je     0x19f35af
   0x00000000019f3578:	mov    (%rdi),%rax
   0x00000000019f357b:	callq  *0xd0(%rax)
   0x00000000019f3581:	mov    0x0(%rbp),%eax
   0x00000000019f3584:	cmp    $0x5,%eax
   0x00000000019f3587:	je     0x19f35f0  <-- that's our jump target!
```

RSI is 0 as per R12.
RDI is 0x7FFFF47E6910.
The pointer at RDI is 0x2430e70.
Adding 0xD0 you get 0x2430F40.
The pointer at there is 0x1A62DA0.

Following that:
```
   0x0000000001a62da0:	test   %rsi,%rsi
   0x0000000001a62da3:	je     0x1a62dc8
   0x0000000001a62da5:	mov    0x50(%rsi),%rax
   0x0000000001a62da9:	mov    0x118(%rdi),%rdi
   0x0000000001a62db0:	xor    %ecx,%ecx
   0x0000000001a62db2:	mov    $0x2,%edx
   0x0000000001a62db7:	mov    (%rax),%rsi
   0x0000000001a62dba:	mov    0x152a5af(%rip),%rax        # 0x2f8d370
   0x0000000001a62dc1:	jmpq   *%rax
...
   0x0000000001a62dc8:	mov    0x118(%rdi),%rdi
   0x0000000001a62dcf:	xor    %ecx,%ecx
   0x0000000001a62dd1:	mov    $0x2,%edx
   0x0000000001a62dd6:	xor    %esi,%esi
   0x0000000001a62dd8:	mov    0x152a591(%rip),%rax        # 0x2f8d370
   0x0000000001a62ddf:	jmpq   *%rax
```

**0x2f8d370 is XSetInputFocus (0x7FFFF77E0320).**

OK, I think that should be enough info to solve both issues.

**Comment by iamgreaser** [comment]
I mostly got distracted by beta testing the upcoming Talos update, however I did manage to fix the issue with in-game mouse clicks being wrong. It's in a branch I've got but I haven't got a PR for it yet.

**Comment by clementgallet** [comment]
Mouse should work correctly now in menus, I forgot to set the window parameter in an event (f54319d77c6bc67d7bb99c27d18ae834e4950d7a). It should fix the crash also.
