### ISSUE TITLE
Stack smashing crash when loading savestates

### ISSUE THREAD

**Issue by AAGaming00** [clementgallet/libTAS#434]
When loading savestates in any game, even glxgears, the game crashes and the libTAS logs show this.
```
❯ libTAS
Interim commit d2c3eb07 built on 2021-07-21
Attempt 1: Connected.
[libTAS f:0] Thread 7606 (main) OpenGL vendor: Mesa/X.org
[libTAS f:0] Thread 7606 (main) OpenGL renderer: llvmpipe (LLVM 12.0.1, 256 bits)
[libTAS f:159] Thread 7606 (main) Saved state 1 of size 4718454 in 0.078455 seconds
[libTAS f:159] Thread 7606 (main) Loaded state 1 in 0.079289 seconds
*** stack smashing detected ***: terminated
recv() returns 0 -> socket closed
Got wrong message after state loading
send() returns -1 with error Broken pipe
send() returns -1 with error Broken pipe
send() returns -1 with error Broken pipe
recv() returns 0 -> socket closed
The connection to the game was closed. Exiting
```
[GDB Backtrace](https://cdn.discordapp.com/attachments/726814175468191815/888833270966525963/message.txt)

**Comment by YaLTeR** [comment]
I can reproduce this in a container (built with fixes from https://github.com/clementgallet/libTAS/pull/437).

**Comment by dwangoac** [comment]
This issue is still present on some systems (as of Interim commit d2e42681 built on 2023-02-27). I have an Asus ROG Zephyrus G15 and launching simpletestgame, creating a savestate, advancing and attempting to load that savestate immediately causes this backtrace:

```c
[New Thread 0x7fff6dffb640 (LWP 112431)]
[libTAS f:0] Thread 112365 (main) OpenGL vendor: Mesa/X.org
[libTAS f:0] Thread 112365 (main) OpenGL renderer: llvmpipe (LLVM 15.0.7, 256 bits)
[libTAS f:2] Thread 112365 (main) Saved state 1 of size 3131065 in 0.274298 seconds
[libTAS f:2] Thread 112365 (main) Loaded state 1 in 0.075774 seconds
*** stack smashing detected ***: terminated

Thread 1 "simplestgame" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737332303936) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737332303936) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737332303936) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737332303936, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7ae8476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7ace7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7b2f6f6 in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7ffff7c81943 "*** %s ***: terminated\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff7bdc76a in __GI___fortify_fail (msg=msg@entry=0x7ffff7c8192b "stack smashing detected")
    at ./debug/fortify_fail.c:26
#7  0x00007ffff7bdc736 in __stack_chk_fail () at ./debug/stack_chk_fail.c:24
#8  0x00007ffff7b3caba in __GI___pthread_kill (threadid=<optimized out>, signo=<optimized out>)
    at ./nptl/pthread_kill.c:90
#9  0x00007ffff7edc0cf in libtas::SaveStateManager::checkpoint (slot=-9392)
    at checkpoint/SaveStateManager.cpp:273
#10 0x00007ffff7eb0f7f in libtas::receive_messages (hud=..., draw=...) at frame.cpp:741
#11 libtas::frameBoundary(std::function<void ()>, libtas::RenderHUD&) (draw=..., hud=...) at frame.cpp:480
#12 0x00007ffff7f0cf90 in libtas::SDL_RenderPresent (renderer=<optimized out>) at sdl/sdlrender.cpp:87
#13 0x00005555555553fc in main ()
```

**Comment by clementgallet** [comment]
Let's centralize this in #522
