### ISSUE TITLE
undefined symbol: _dl_sym on Fedora 35

### ISSUE THREAD

**Issue by YaLTeR** [clementgallet/libTAS#435]
```
Interim commit a7bc36ba built on 2021-09-29
/usr/bin/glxgears: symbol lookup error: /var/home/yalter/source/cpp/libTAS/install-f35/bin/libtas.so: undefined symbol: _dl_sym
```

**Comment by clementgallet** [comment]
Could you tell me if Fedora 35 is bundled with glibc, and which version it is using?

**Comment by YaLTeR** [comment]
Yeah, it uses glibc.
```
└─ rpm -q glibc
glibc-2.34-6.fc35.x86_64
glibc-2.34-6.fc35.i686
```

**Comment by clementgallet** [comment]
glibc 2.33:
```extern void *_dl_sym (void *handle, const char *name, void *who);```

glibc 2.34:
```extern void *_dl_sym (void *handle, const char *name, void *who) attribute_hidden;```

with

```#if defined SHARED || defined LIBC_NONSHARED \
  || (BUILD_PIE_DEFAULT && IS_IN (libc))
# define attribute_hidden __attribute__ ((visibility ("hidden")))
#else
# define attribute_hidden
#endif```

**Comment by clementgallet** [comment]
Alternative way of getting addresses of `dlopen()` and `dlsym()` is to manually look at symbols inside the loaded library. See how MandoHud is doing: https://github.com/flightlessmango/MangoHud/blob/master/src/real_dlsym.cpp

**Comment by BenLubar** [comment]
I updated to Ubuntu 21.10 and am now getting `symbol lookup error: /usr/bin/libtas32.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE`

**Comment by clementgallet** [comment]
I integrated the above method in 4e8310a. It works fine for me but I didn't test those recent glibc versions.

**Comment by BenLubar** [comment]
trying to start undertale on b32ca0dd683fd92085902125babb5c1b73e09a9b:

```
Thread 1 "runner" received signal SIGSEGV, Segmentation fault.
0xec675f53 in llvm::Value::setNameImpl(llvm::Twine const&) () from /lib/i386-linux-gnu/libLLVM-12.so.1
(gdb) bt
#0  0xec675f53 in llvm::Value::setNameImpl(llvm::Twine const&) () from /lib/i386-linux-gnu/libLLVM-12.so.1
#1  0xf0f62ff4 in ?? () from /lib/i386-linux-gnu/libLLVM-12.so.1
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

```
Thread 1 "runner" received signal SIGSEGV, Segmentation fault.
0xec675f53 in llvm::Value::setNameImpl(llvm::Twine const&) () from /lib/i386-linux-gnu/libLLVM-12.so.1
(gdb) bt
#0  0xec675f53 in llvm::Value::setNameImpl(llvm::Twine const&) () from /lib/i386-linux-gnu/libLLVM-12.so.1
#1  0x00000020 in ?? ()
#2  0x08944090 in ?? ()
#3  0x40000000 in ?? ()
#4  0xec675f5a in llvm::Value::setNameImpl(llvm::Twine const&) () from /lib/i386-linux-gnu/libLLVM-12.so.1
#5  0x40400000 in ?? ()
#6  0x0000000e in ?? ()
#7  0xf0f7e9c0 in llvm::DisableABIBreakingChecks () from /lib/i386-linux-gnu/libLLVM-12.so.1
#8  0xec675f5a in llvm::Value::setNameImpl(llvm::Twine const&) () from /lib/i386-linux-gnu/libLLVM-12.so.1
#9  0xf693f768 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

```
Thread 1 "runner" received signal SIGSEGV, Segmentation fault.
__strlen_sse2_bsf () at ../sysdeps/i386/i686/multiarch/strlen-sse2-bsf.S:50
50      ../sysdeps/i386/i686/multiarch/strlen-sse2-bsf.S: No such file or directory.
(gdb) bt
#0  __strlen_sse2_bsf () at ../sysdeps/i386/i686/multiarch/strlen-sse2-bsf.S:50
#1  0xf125ac7a in ?? () from /usr/lib/i386-linux-gnu/dri/swrast_dri.so
#2  0x083059b9 in ?? ()
#3  0x083066e2 in ?? ()
#4  0x08306c52 in ?? ()
#5  0x08306cca in ?? ()
#6  0x083002a0 in ?? ()
#7  0x082fd633 in ?? ()
#8  0x081001fa in ?? ()
#9  0x081be8c3 in ?? ()
#10 0x082f7eda in ?? ()
#11 0x0831d356 in ?? ()
#12 0xf73544ca in __libc_start_call_main (main=main@entry=0x831d180, argc=argc@entry=1, argv=argv@entry=0xffffd1b4) at ../sysdeps/nptl/libc_start_call_main.h:58
#13 0xf73545aa in __libc_start_main_impl (main=0x831d180, argc=1, argv=0xffffd1b4, init=0x8351350, fini=0x83513c0, rtld_fini=0xf7fda730 <_dl_fini>, stack_end=0xffffd1ac) at ../csu/libc-start.c:409
#14 0x08051525 in ?? ()
```

```
Thread 1 "runner" received signal SIGSEGV, Segmentation fault.
0xec60ad29 in llvm::GetElementPtrInst::init(llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&) () from /lib/i386-linux-gnu/libLLVM-12.so.1
(gdb) bt
#0  0xec60ad29 in llvm::GetElementPtrInst::init(llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&) () from /lib/i386-linux-gnu/libLLVM-12.so.1
#1  0xffff948c in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

getting a different crash every time, but so far I haven't had any successful process startups

**Comment by YaLTeR** [comment]
Works for me now on F35, so closing this issue.

Of course there's still stack smashing on state load but that's https://github.com/clementgallet/libTAS/issues/434.
