### ISSUE TITLE
Cannot access memory at address when running on pipewire

### ISSUE THREAD

**Issue by marcelopio** [clementgallet/libTAS#463]
Running Dandara on Pipewire makes libTAS access wrong memory address
```
#0  0x00007ffff7928d22 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7912862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7ed38ef in std::__replacement_assert (__condition=0x7ffff7f43883 "__n < this->size()",
__function=0x7ffff7f45e20 "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::vector<_Tp, _Alloc"..., __line=1045, __file=0x7ffff7f45d68 "/usr/include/c++/11.1.0/bits/stl_vector.h")
at /usr/include/c++/11.1.0/x86_64-pc-linux-gnu/bits/c++config.h:504
#3  std::vector<unsigned char, std::allocator<unsigned char> >::operator[] (this=0x7ffff690aa38,
__n=<optimized out>) at /usr/include/c++/11.1.0/bits/stl_vector.h:1045
#4  std::vector<unsigned char, std::allocator<unsigned char> >::operator[] (__n=<optimized out>,
this=0x7ffff690aa38) at /usr/include/c++/11.1.0/bits/stl_vector.h:1043
#5  libtas::AudioBuffer::getSamples (this=this@entry=0x7ffff690aa20,
outSamples=@0x7fffffffd328: 0xf7fe006c <error: Cannot access memory at address 0xf7fe006c>,
nbSamples=nbSamples@entry=800, position=position@entry=1024, loopstatic=<optimized out>)
at audio/AudioBuffer.cpp:132
#6  0x00007ffff7ed65f5 in libtas::AudioSource::mixWith (this=0x7ffff6533390, ticks=...,
outSamples=0x7fff6c741b30 "", outBytes=2940, outBitDepth=16, outNbChannels=2, outFrequency=44100,
outVolume=<optimized out>) at audio/AudioSource.cpp:227
#7  0x00007ffff7ed45fb in libtas::AudioContext::mixAllSources (this=0x7ffff7fb4640 <libtas::audiocontext>,
ticks=...) at /usr/include/c++/11.1.0/bits/stl_vector.h:1045
#8  0x00007ffff7ec0559 in libtas::frameBoundary(std::function<void ()>, libtas::RenderHUD&) (draw=...,
hud=...) at frame.cpp:227
#9  0x00007ffff7f1d349 in libtas::SDL_GL_SwapWindow (window=<optimized out>) at sdl/sdlwindows.cpp:101
#10 0x000000000095c207 in ?? ()
```

Logs:
https://pastebin.com/Nc0RTHaa

**Comment by marcelopio** [comment]
Tested with c98e6e7, this issue was solved!
