### ISSUE TITLE
Floating point exception with RAM Search

### ISSUE THREAD

**Issue by Fly0DB** [clementgallet/libTAS#488]
OS: Arch Linux
CPU: AMD FX-4330 Quad-Core Processor
GPU and driver: GTX 1050 Ti with Nouveau

When I run an application (I tested with PCem and DOSBox) and try to use RAM Search (set Specific Value 50 and press New), libTAS almost always crashes with the error: "Floating point exception (core dumped)".
However, in rare cases it works, and if it does, then libTAS won't crash until restart (i.e. I can stop PCem and run DOSBox and RAM Search will work there).

**Comment by Fly0DB** [comment]
Tried latest commit (2022-05-30), the error still occurs.

GDB output:
```
Thread 1 "libTAS" received signal SIGFPE, Arithmetic exception.
0x000055555560e4aa in MemScanner::scan_count (this=0x555555b0b5c0) at ramsearch/MemScanner.cpp:250
250         return total_size / value_type_size;
(gdb) thread apply all bt

Thread 5 (Thread 0x7fffe8d61640 (LWP 66882) "libTAS"):
#0  0x00007ffff62d8625 in clock_nanosleep () from /usr/lib/libc.so.6
#1  0x00007ffff62dd1e7 in nanosleep () from /usr/lib/libc.so.6
#2  0x000055555558fa93 in GameLoop::sleepSendPreview (this=0x5555557b9420) at GameLoop.cpp:516
#3  0x0000555555591b2e in GameLoop::start (this=0x5555557b9420) at GameLoop.cpp:106
#4  0x00007ffff66d6183 in std::execute_native_thread_routine (__p=0x555555b76ba0) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
#5  0x00007ffff628c54d in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff6311b14 in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffe97a1640 (LWP 66871) "libTAS:disk$0"):
#0  0x00007ffff6289119 in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff628b920 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x00007fffe26b28cc in ?? () from /usr/lib/dri/nouveau_dri.so
#3  0x00007fffe26ac05c in ?? () from /usr/lib/dri/nouveau_dri.so
#4  0x00007ffff628c54d in ?? () from /usr/lib/libc.so.6
#5  0x00007ffff6311b14 in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffeb4fe640 (LWP 66870) "QDBusConnection"):
#0  0x00007ffff6305faf in poll () from /usr/lib/libc.so.6
#1  0x00007ffff5b6ef68 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007ffff5b16392 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007ffff6cd87bc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff6c8679c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#5  0x00007ffff6ae753f in QThread::exec() () from /usr/lib/libQt5Core.so.5
#6  0x00007ffff392675a in ?? () from /usr/lib/libQt5DBus.so.5
#7  0x00007ffff6ae436a in ?? () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff628c54d in ?? () from /usr/lib/libc.so.6
#9  0x00007ffff6311b14 in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7ffff338e640 (LWP 66868) "QXcbEventQueue"):
#0  0x00007ffff6305faf in poll () from /usr/lib/libc.so.6
#1  0x00007ffff7f0720b in ?? () from /usr/lib/libxcb.so.1
#2  0x00007ffff7f08ccd in xcb_wait_for_event () from /usr/lib/libxcb.so.1
#3  0x00007ffff352ea12 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#4  0x00007ffff6ae436a in ?? () from /usr/lib/libQt5Core.so.5
#5  0x00007ffff628c54d in ?? () from /usr/lib/libc.so.6
--Type <RET> for more, q to quit, c to continue without paging--c
#6  0x00007ffff6311b14 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff6149840 (LWP 66867) "libTAS"):
#0  0x000055555560e4aa in MemScanner::scan_count (this=0x555555b0b5c0) at ramsearch/MemScanner.cpp:250
#1  0x00005555555fa069 in RamSearchModel::scanCount (this=<optimized out>) at ui/RamSearchModel.cpp:81
#2  0x00005555555fa698 in RamSearchWindow::slotNew (this=0x555555b90910) at ui/RamSearchWindow.cpp:229
#3  0x00007ffff6cbe791 in ?? () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff7a5c617 in QAbstractButton::clicked(bool) () from /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff7a5eb0a in ?? () from /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff7a6043d in ?? () from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff7a605e0 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff79af677 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff7978a7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff797e289 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff6c8dff8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff797c287 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff79cd345 in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff79cf0ee in ?? () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff7978a7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff6c8dff8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#17 0x00007ffff713efdc in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#18 0x00007ffff7128945 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#19 0x00007ffff3530df0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#20 0x00007ffff5b18c6b in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#21 0x00007ffff5b6f001 in ?? () from /usr/lib/libglib-2.0.so.0
#22 0x00007ffff5b16392 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#23 0x00007ffff6cd87bc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#24 0x00007ffff6c8679c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#25 0x00007ffff6c912a9 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#26 0x000055555558366c in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:399
```
